INSERT INTO roles(name) VALUES ('CUSTOMER'), ('ADMIN') ON DUPLICATE KEY UPDATE name = name;

INSERT INTO categories(name, slug, description) VALUES
('Casual Wear', 'casual-wear', 'Everyday comfort and refined pet apparel'),
('Ethnic Wear', 'ethnic-wear', 'Festive Indian occasion wear for pets'),
('Rainwear', 'rainwear', 'Monsoon-ready protection for muddy walks'),
('Winter Wear', 'winter-wear', 'Soft knit warmth for colder days'),
('Care', 'care', 'Cleaning and daily care essentials'),
('Home Comfort', 'home-comfort', 'Comfort pieces for calm homes'),
('Accessories', 'accessories', 'Leashes, harnesses, bandanas, and add-ons'),
('Travel Essentials', 'travel-essentials', 'Adventure and road-trip essentials')
ON DUPLICATE KEY UPDATE name = name;

INSERT INTO products(category_id, sku, name, slug, description, highlights, care_info, ideal_use, seo_description, price, stock_quantity, is_featured, is_visible, image_url) VALUES
((SELECT id FROM categories WHERE slug='casual-wear'), 'MI-02', 'MI-02 Everyday Tail Shirt', 'mi-02-everyday-tail-shirt', 'Designed for slower mornings, cafe strolls, and everyday comfort. Lightweight, breathable, and quietly refined for pets who are part of every little moment.', 'Soft breathable cotton blend; Relaxed comfort fit; Lightweight everyday wear; Minimal timeless styling; Easy movement silhouette', 'Fabric: Premium cotton blend. Care: Gentle machine wash recommended. Air dry only.', 'Everyday walks; Cafe outings; Indoor lounging; Weekend travel', 'Buy premium casual dog shirts online in India. Breathable minimalist petwear designed for everyday comfort by Fur & Found.', 999.00, 32, TRUE, TRUE, 'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?auto=format&fit=crop&w=900&q=80'),
((SELECT id FROM categories WHERE slug='casual-wear'), 'MI-03', 'MI-03 Weekend Stroll Shirt', 'mi-03-weekend-stroll-shirt', 'Made for warm afternoons and unhurried walks together. Soft comfort meets effortless styling for easy everyday moments.', 'Lightweight breathable fabric; Relaxed silhouette; Comfortable all-day wear; Movement-friendly design', 'Fabric: Soft cotton blend. Care: Hand wash recommended.', 'Daily wear; Slow weekend outings; Brunch walks; Vacation styling', 'Premium dog shirts online in India with lightweight everyday comfort and modern styling.', 999.00, 28, TRUE, TRUE, 'https://images.unsplash.com/photo-1534361960057-19889db9621e?auto=format&fit=crop&w=900&q=80'),
((SELECT id FROM categories WHERE slug='casual-wear'), 'MI-08', 'MI-08 EarthTone Everyday Wear', 'mi-08-earthtone-everyday-wear', 'Inspired by calm homes, earthy palettes, and quiet luxury. A breathable everyday piece with understated elegance.', 'Earth-tone color palette; Breathable lightweight comfort; Minimal aesthetic design; Everyday versatile styling', 'Fabric: Cotton linen blend. Care: Gentle wash recommended.', 'Everyday wear; Lifestyle photoshoots; Indoor comfort; Calm cozy moments', 'Shop premium earth-tone dog apparel online in India by Fur & Found.', 899.00, 24, FALSE, TRUE, 'https://images.unsplash.com/photo-1517849845537-4d257902454a?auto=format&fit=crop&w=900&q=80'),
((SELECT id FROM categories WHERE slug='casual-wear'), 'MI-09', 'MI-09 Cozy Companion Shirt', 'mi-09-cozy-companion-shirt', 'Soft everyday comfort designed for cuddles, naps, and little adventures.', 'Soft-touch breathable fabric; Relaxed comfort fit; Lightweight daily wear; Easy movement construction', 'Fabric: Soft cotton. Care: Gentle machine wash.', 'Daily walks; Indoor lounging; Travel comfort; Everyday styling', 'Premium everyday dog shirts online in India with soft lightweight comfort.', 899.00, 24, FALSE, TRUE, 'https://images.unsplash.com/photo-1541599540903-216a46ca1dc0?auto=format&fit=crop&w=900&q=80'),
((SELECT id FROM categories WHERE slug='ethnic-wear'), 'MI-11', 'MI-11 Royal Festive Kurta', 'mi-11-royal-festive-kurta', 'Made for celebrations, family photos, and unforgettable festive moments with lightweight traditional elegance.', 'Elegant festive silhouette; Lightweight breathable comfort; Traditional-inspired detailing; Comfortable all-day wear', 'Fabric: Cotton silk blend. Care: Dry clean preferred.', 'Weddings; Diwali celebrations; Festive gatherings; Family photoshoots', 'Buy luxury dog kurtas online in India for weddings and celebrations.', 1299.00, 18, FALSE, TRUE, 'https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&w=900&q=80'),
((SELECT id FROM categories WHERE slug='ethnic-wear'), 'MI-14', 'MI-14 Heritage Celebration Wear', 'mi-14-heritage-celebration-wear', 'Traditional elegance reimagined for modern pet families with breathable festive comfort.', 'Traditional festive design; Breathable lightweight fabric; Elegant handcrafted feel; Comfortable relaxed fit', 'Fabric: Cotton blend. Care: Gentle hand wash recommended.', 'Festivals; Wedding celebrations; Family gatherings; Festive photoshoots', 'Festive dog clothing online in India by Fur & Found.', 1199.00, 18, FALSE, TRUE, 'https://images.unsplash.com/photo-1507146426996-ef05306b995a?auto=format&fit=crop&w=900&q=80'),
((SELECT id FROM categories WHERE slug='ethnic-wear'), 'MI-27', 'MI-27 Celebration Sherwani', 'mi-27-celebration-sherwani', 'Crafted for weddings, celebrations, and moments worth remembering.', 'Premium festive detailing; Comfortable lightweight structure; Elegant sherwani silhouette; Breathable festive comfort', 'Fabric: Cotton silk blend. Care: Dry clean only.', 'Weddings; Engagement ceremonies; Festive events; Premium celebrations', 'Luxury dog sherwanis online in India for grand celebrations.', 1499.00, 12, FALSE, TRUE, 'https://images.unsplash.com/photo-1568572933382-74d440642117?auto=format&fit=crop&w=900&q=80'),
((SELECT id FROM categories WHERE slug='rainwear'), 'MI-42', 'MI-42 Monsoon Explorer Raincoat', 'mi-42-monsoon-explorer-raincoat', 'Designed for rainy walks, muddy paws, and monsoon adventures in Indian weather.', 'Waterproof outer shell; Breathable comfort lining; Adjustable secure fit; Lightweight movement-friendly design; Easy leash access', 'Fabric: Waterproof nylon blend. Care: Wipe clean recommended.', 'Monsoon walks; Outdoor adventures; Rainy city strolls; Travel', 'Premium dog raincoats online in India for monsoon walks.', 1299.00, 26, TRUE, TRUE, 'https://images.unsplash.com/photo-1504595403659-9088ce801e29?auto=format&fit=crop&w=900&q=80'),
((SELECT id FROM categories WHERE slug='rainwear'), 'MI-43', 'MI-43 StormGuard Rainwear', 'mi-43-stormguard-rainwear', 'Everyday monsoon protection with effortless style for pets who keep exploring.', 'Waterproof construction; Lightweight breathable comfort; Reflective detailing; Comfortable everyday fit', 'Fabric: Waterproof polyester blend. Care: Wipe clean only.', 'Monsoon season; City walks; Outdoor travel; Rainy adventures', 'Shop waterproof dog rain jackets online in India.', 1299.00, 22, FALSE, TRUE, 'https://images.unsplash.com/photo-1537151608828-ea2b11777ee8?auto=format&fit=crop&w=900&q=80'),
((SELECT id FROM categories WHERE slug='winter-wear'), 'MI-47', 'MI-47 Honeybee Hug Sweater', 'mi-47-honeybee-hug-sweater', 'Soft winter warmth for cozy mornings and colder evenings.', 'Soft acrylic wool blend; Breathable winter warmth; Lightweight layering comfort; Stretch movement fit', 'Fabric: Acrylic wool blend. Care: Gentle hand wash recommended.', 'Winter walks; Indoor lounging; Cozy evenings; Travel comfort', 'Buy premium dog sweaters online in India by Fur & Found.', 1099.00, 20, FALSE, TRUE, 'https://images.unsplash.com/photo-1558788353-f76d92427f16?auto=format&fit=crop&w=900&q=80'),
((SELECT id FROM categories WHERE slug='winter-wear'), 'MI-48', 'MI-48 CruiseLine Knit Sweater', 'mi-48-cruiseline-knit-sweater', 'Inspired by mountain mornings and slower winter living.', 'Premium knit texture; Soft breathable warmth; Relaxed comfort fit; Lightweight winter layering', 'Fabric: Acrylic wool blend. Care: Hand wash recommended.', 'Winter mornings; Cafe outings; Indoor warmth; Everyday winter wear', 'Luxury winter sweaters for dogs online in India.', 1199.00, 20, FALSE, TRUE, 'https://images.unsplash.com/photo-1561037404-61cd46aa615b?auto=format&fit=crop&w=900&q=80'),
((SELECT id FROM categories WHERE slug='winter-wear'), 'MI-49', 'MI-49 EarthBound Stripes Sweater', 'mi-49-earthbound-stripes-sweater', 'Timeless winter knitwear inspired by earthy calm aesthetics.', 'Soft knit fabric; Earth-tone striped detailing; Lightweight winter warmth; Comfortable movement fit', 'Fabric: Acrylic wool blend. Care: Gentle hand wash only.', 'Everyday winter wear; Indoor lounging; Cozy travel moments; Winter styling', 'Striped dog sweaters online in India with modern minimalist styling.', 1199.00, 20, FALSE, TRUE, 'https://images.unsplash.com/photo-1546975490-e8b92a360b24?auto=format&fit=crop&w=900&q=80'),
((SELECT id FROM categories WHERE slug='winter-wear'), 'MI-50', 'MI-50 Morning Glow Knit Sweater', 'mi-50-morning-glow-knit-sweater', 'Inspired by soft sunlight, warm homes, and cozy winter moments.', 'Soft-touch knit texture; Lightweight breathable warmth; Relaxed everyday fit; Comfortable winter layering', 'Fabric: Acrylic wool blend. Care: Gentle wash recommended.', 'Morning walks; Cozy evenings; Indoor warmth; Everyday wear', 'Warm knit sweaters for dogs online in India.', 1099.00, 20, FALSE, TRUE, 'https://images.unsplash.com/photo-1530281700549-e82e7bf110d6?auto=format&fit=crop&w=900&q=80'),
((SELECT id FROM categories WHERE slug='home-comfort'), 'BATH-01', 'Cloud Bathrobe', 'cloud-bathrobe', 'A comfort-lifestyle bathrobe for clean post-bath cuddles and slow home moments.', 'Water-absorbent comfort; Cozy robe fit; Gentle on fur; Premium home aesthetic', 'Fabric: Absorbent cotton blend. Care: Gentle machine wash and air dry.', 'After baths; Rainy walks; Grooming days; Home comfort', 'Premium dog bathrobe online in India for bath and home comfort.', 999.00, 18, TRUE, TRUE, 'https://images.unsplash.com/photo-1505628346881-b72b27e84530?auto=format&fit=crop&w=900&q=80'),
((SELECT id FROM categories WHERE slug='care'), 'CARE-01', 'Paw Cleaner Kit', 'paw-cleaner-kit', 'A high-frequency daily care kit for muddy paws, apartment homes, cars, and monsoon walks.', 'Everyday paw cleaning; Travel-friendly; Gentle care routine; Refill-ready usage', 'Rinse cleaner after use. Store spray and tools in a cool dry place.', 'Daily walks; Monsoon season; Car rides; Post-park cleanups', 'Dog paw cleaner kit online in India for daily muddy paw care.', 999.00, 36, TRUE, TRUE, 'https://images.unsplash.com/photo-1583337130417-3346a1be7dee?auto=format&fit=crop&w=900&q=80'),
((SELECT id FROM categories WHERE slug='accessories'), 'FOUND-01', 'Found Track Harness', 'found-track-harness', 'Adventure freely and stay connected with a premium walk essential for outdoor pets.', 'Adventure-ready fit; Secure walking support; Premium details; Designed for road trips and hikes', 'Wipe clean after outdoor use. Check fittings before every walk.', 'Outdoor walks; Hiking; Travel; Daily adventures', 'Premium dog harness online in India for adventure walks and travel.', 1499.00, 16, TRUE, TRUE, 'https://images.unsplash.com/photo-1556866261-8763a7662333?auto=format&fit=crop&w=900&q=80'),
((SELECT id FROM categories WHERE slug='accessories'), 'BAND-01', 'Personalized Name Bandana', 'personalized-name-bandana', 'An affordable add-on and gifting favorite for pets with personality.', 'Personalized styling; Gift-friendly; Lightweight comfort; Photo-ready accessory', 'Hand wash gently. Air dry flat.', 'Gifting; Birthdays; Cafe visits; Everyday styling', 'Personalized dog bandana online in India by Fur & Found.', 499.00, 40, FALSE, TRUE, 'https://images.unsplash.com/photo-1518717758536-85ae29035b6d?auto=format&fit=crop&w=900&q=80'),
((SELECT id FROM categories WHERE slug='home-comfort'), 'BED-01', 'Calm Home Bed', 'calm-home-bed', 'A soft home-comfort essential for quiet naps, cozy corners, and slow days indoors.', 'Soft supportive base; Minimal home-friendly design; Cozy nap surface; Everyday comfort', 'Spot clean regularly. Air out in sunlight when needed.', 'Naps; Living rooms; Bedrooms; Calm home corners', 'Premium dog bed online in India for home comfort.', 1799.00, 14, FALSE, TRUE, 'https://images.unsplash.com/photo-1525253086316-d0c936c814f8?auto=format&fit=crop&w=900&q=80')
ON DUPLICATE KEY UPDATE name = name;

INSERT INTO travel_partners(name, slug, location, description, is_active) VALUES
('A Dogs Story', 'a-dogs-story-mussoorie', 'Mussoorie', 'Built around pet travel and ideal for premium Fur & Found travel experiences.', TRUE),
('Karma Chalets', 'karma-chalets', 'NCR', 'A popular weekend destination with open spaces and a strong pet-parent audience.', TRUE),
('Ayatana Coorg', 'ayatana-coorg', 'Coorg, Karnataka', 'Premium nature-luxury positioning for curated pet-friendly getaways.', TRUE),
('Emerald Trail', 'emerald-trail-bhimtal', 'Bhimtal', 'A pet-friendly North India resort fit for relaxed road-trip itineraries.', TRUE),
('Our Native Village', 'our-native-village', 'Bengaluru', 'Eco and pet-friendly destination with a strong local market fit.', TRUE),
('Sherlock', 'sherlock-ooty', 'Ooty', 'A hill-station stay for pet parents planning classic road trips.', TRUE),
('Great Trails Kodaikanal', 'great-trails-kodaikanal', 'Kodaikanal', 'Premium hill-station property for family and pet-friendly travel.', TRUE),
('Suryagarh', 'suryagarh', 'Jaisalmer', 'Aspirational luxury partner for elevated brand perception.', TRUE),
('The Fern Samali Resort Dapoli', 'the-fern-samali-resort-dapoli', 'Dapoli, Maharashtra', 'Coastal weekend-travel partner for Maharashtra pet parents.', TRUE),
('Praana Experience', 'praana-experience', 'Boutique India', 'Boutique, highly visual stay for premium pet-travel storytelling.', TRUE)
ON DUPLICATE KEY UPDATE name = name;

INSERT INTO blog_posts(title, slug, excerpt, content, is_featured) VALUES
('Why Dogs Teach Us to Slow Down', 'why-dogs-teach-us-to-slow-down', 'A gentle journal note on living slower with pets.', 'Pets turn ordinary routines into rituals: walks, meals, naps, and the quiet pause before the next adventure.', TRUE),
('The Story of India''s Indie Dogs', 'the-story-of-indias-indie-dogs', 'A tribute to resilient, loving indie companions.', 'India''s indie dogs carry stories of loyalty, street-smart courage, and deep companionship.', TRUE),
('Why Every Dog Deserves a Vacation', 'why-every-dog-deserves-a-vacation', 'Pet-friendly travel is not just a trend. It is a way to include family.', 'From safe stays to road-trip rituals, travelling with pets can be calmer when the details are planned well.', TRUE)
ON DUPLICATE KEY UPDATE title = title;

INSERT INTO users(full_name, email, password_hash, phone, role_id) VALUES
('Admin User', 'admin@furandfound.com', '$2a$10$Q7sR8eGU7dJvVKBt6R2CYO06tFEiGfxd68GYJm9kPgG9V8oXjE3o2', '9999999999', (SELECT id FROM roles WHERE name = 'ADMIN')),
('Demo Customer', 'customer@furandfound.com', '$2a$10$Q7sR8eGU7dJvVKBt6R2CYO06tFEiGfxd68GYJm9kPgG9V8oXjE3o2', '8888888888', (SELECT id FROM roles WHERE name = 'CUSTOMER'))
ON DUPLICATE KEY UPDATE email = email;
